.TH "include Directory Reference" 3 "Tue Jul 21 2015" "datetimetz-converter-lib-0.9" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconfig\&.h\fP"
.br
.ti -1c
.RI "file \fBlibdatetimetz_converter_consistency\&.h\fP"
.br
.RI "\fIProvides some functions to compare results after timezone conversion\&. \fP"
.ti -1c
.RI "file \fBlibdatetimetz_converter_epoch\&.h\fP"
.br
.RI "\fIProvides some functions to convert timestamp to Epoch\&. \fP"
.ti -1c
.RI "file \fBlibdatetimetz_converter_iso8601assert\&.h\fP"
.br
.RI "\fIProvides some functions to validate the requirements before the conversion\&. \fP"
.ti -1c
.RI "file \fBlibdatetimetz_converter_iso8601verifier\&.h\fP"
.br
.RI "\fIProvides some functions to compare results after timezone conversion\&. \fP"
.ti -1c
.RI "file \fBlibdatetimetz_converter_lib\&.h\fP"
.br
.ti -1c
.RI "file \fBlibdatetimetz_converter_prereqs\&.h\fP"
.br
.RI "\fIProvides some functions to validate the requirements before the conversion\&. \fP"
.ti -1c
.RI "file \fBlibdatetimetz_converter_tzanytype\&.h\fP"
.br
.RI "\fIProvides some functions to handle timestamps defined with any type of timezone\&. \fP"
.ti -1c
.RI "file \fBLinkDef\&.h\fP"
.br
.in -1c
