.TH "include/config.h" 3 "Sun Jul 26 2015" "datetimetz-converter-lib-0.5.3" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/config.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHAVE_ALARM\fP"
.br
.ti -1c
.RI "#define \fBHAVE_DLFCN_H\fP"
.br
.ti -1c
.RI "#define \fBHAVE_INTTYPES_H\fP"
.br
.ti -1c
.RI "#define \fBHAVE_MALLOC\fP"
.br
.ti -1c
.RI "#define \fBHAVE_MEMORY_H\fP"
.br
.ti -1c
.RI "#define \fBHAVE_REALLOC\fP"
.br
.ti -1c
.RI "#define \fBHAVE_REGCOMP\fP"
.br
.ti -1c
.RI "#define \fBHAVE_REGEX_H\fP"
.br
.ti -1c
.RI "#define \fBHAVE_SETENV\fP"
.br
.ti -1c
.RI "#define \fBHAVE_STDINT_H\fP"
.br
.ti -1c
.RI "#define \fBHAVE_STDIO_H\fP"
.br
.ti -1c
.RI "#define \fBHAVE_STDLIB_H\fP"
.br
.ti -1c
.RI "#define \fBHAVE_STRINGS_H\fP"
.br
.ti -1c
.RI "#define \fBHAVE_STRING_H\fP"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_STAT_H\fP"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_TIME_H\fP"
.br
.ti -1c
.RI "#define \fBHAVE_SYS_TYPES_H\fP"
.br
.ti -1c
.RI "#define \fBHAVE_TIME_H\fP"
.br
.ti -1c
.RI "#define \fBHAVE_UNAME\fP"
.br
.ti -1c
.RI "#define \fBHAVE_UNISTD_H\fP"
.br
.ti -1c
.RI "#define \fBLT_OBJDIR\fP"
.br
.ti -1c
.RI "#define \fBPACKAGE\fP"
.br
.ti -1c
.RI "#define \fBPACKAGE_BUGREPORT\fP"
.br
.ti -1c
.RI "#define \fBPACKAGE_NAME\fP"
.br
.ti -1c
.RI "#define \fBPACKAGE_STRING\fP"
.br
.ti -1c
.RI "#define \fBPACKAGE_TARNAME\fP"
.br
.ti -1c
.RI "#define \fBPACKAGE_URL\fP"
.br
.ti -1c
.RI "#define \fBPACKAGE_VERSION\fP"
.br
.ti -1c
.RI "#define \fBSTDC_HEADERS\fP"
.br
.ti -1c
.RI "#define \fBTIME_WITH_SYS_TIME\fP"
.br
.ti -1c
.RI "#define \fB_ALL_SOURCE\fP"
.br
.ti -1c
.RI "#define \fB_GNU_SOURCE\fP"
.br
.ti -1c
.RI "#define \fB_POSIX_PTHREAD_SEMANTICS\fP"
.br
.ti -1c
.RI "#define \fB_TANDEM_SOURCE\fP"
.br
.ti -1c
.RI "#define \fB__EXTENSIONS__\fP"
.br
.ti -1c
.RI "#define \fBVERSION\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __EXTENSIONS__"

.PP
Definition at line 115 of file config\&.h\&.
.SS "#define _ALL_SOURCE"

.PP
Definition at line 99 of file config\&.h\&.
.SS "#define _GNU_SOURCE"

.PP
Definition at line 103 of file config\&.h\&.
.SS "#define _POSIX_PTHREAD_SEMANTICS"

.PP
Definition at line 107 of file config\&.h\&.
.SS "#define _TANDEM_SOURCE"

.PP
Definition at line 111 of file config\&.h\&.
.SS "#define HAVE_ALARM"

.PP
Definition at line 5 of file config\&.h\&.
.SS "#define HAVE_DLFCN_H"

.PP
Definition at line 8 of file config\&.h\&.
.SS "#define HAVE_INTTYPES_H"

.PP
Definition at line 11 of file config\&.h\&.
.SS "#define HAVE_MALLOC"

.PP
Definition at line 15 of file config\&.h\&.
.SS "#define HAVE_MEMORY_H"

.PP
Definition at line 18 of file config\&.h\&.
.SS "#define HAVE_REALLOC"

.PP
Definition at line 22 of file config\&.h\&.
.SS "#define HAVE_REGCOMP"

.PP
Definition at line 25 of file config\&.h\&.
.SS "#define HAVE_REGEX_H"

.PP
Definition at line 28 of file config\&.h\&.
.SS "#define HAVE_SETENV"

.PP
Definition at line 31 of file config\&.h\&.
.SS "#define HAVE_STDINT_H"

.PP
Definition at line 34 of file config\&.h\&.
.SS "#define HAVE_STDIO_H"

.PP
Definition at line 37 of file config\&.h\&.
.SS "#define HAVE_STDLIB_H"

.PP
Definition at line 40 of file config\&.h\&.
.SS "#define HAVE_STRING_H"

.PP
Definition at line 46 of file config\&.h\&.
.SS "#define HAVE_STRINGS_H"

.PP
Definition at line 43 of file config\&.h\&.
.SS "#define HAVE_SYS_STAT_H"

.PP
Definition at line 49 of file config\&.h\&.
.SS "#define HAVE_SYS_TIME_H"

.PP
Definition at line 52 of file config\&.h\&.
.SS "#define HAVE_SYS_TYPES_H"

.PP
Definition at line 55 of file config\&.h\&.
.SS "#define HAVE_TIME_H"

.PP
Definition at line 58 of file config\&.h\&.
.SS "#define HAVE_UNAME"

.PP
Definition at line 61 of file config\&.h\&.
.SS "#define HAVE_UNISTD_H"

.PP
Definition at line 64 of file config\&.h\&.
.SS "#define LT_OBJDIR"

.PP
Definition at line 68 of file config\&.h\&.
.SS "#define PACKAGE"

.PP
Definition at line 71 of file config\&.h\&.
.SS "#define PACKAGE_BUGREPORT"

.PP
Definition at line 74 of file config\&.h\&.
.SS "#define PACKAGE_NAME"

.PP
Definition at line 77 of file config\&.h\&.
.SS "#define PACKAGE_STRING"

.PP
Definition at line 80 of file config\&.h\&.
.SS "#define PACKAGE_TARNAME"

.PP
Definition at line 83 of file config\&.h\&.
.SS "#define PACKAGE_URL"

.PP
Definition at line 86 of file config\&.h\&.
.SS "#define PACKAGE_VERSION"

.PP
Definition at line 89 of file config\&.h\&.
.SS "#define STDC_HEADERS"

.PP
Definition at line 92 of file config\&.h\&.
.SS "#define TIME_WITH_SYS_TIME"

.PP
Definition at line 95 of file config\&.h\&.
.SS "#define VERSION"

.PP
Definition at line 120 of file config\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for datetimetz-converter-lib-0\&.5\&.3 from the source code\&.
