.TH "Converter for Timestamp (Date-Time)" 3 "Tue Jul 21 2015" "datetimetz-converter-lib-0.5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Converter for Timestamp (Date-Time) \- 
.PP
Provides some functions to convert timestamp between timezone, using the zoneinfo databases\&.  

.SS "Files"

.in +1c
.ti -1c
.RI "file \fBlibdatetimetz_converter_epoch\&.h\fP"
.br
.RI "\fIProvides some functions to convert timestamp to Epoch\&. \fP"
.ti -1c
.RI "file \fBlibdatetimetz_converter_iso8601assert\&.h\fP"
.br
.RI "\fIProvides some functions to validate the requirements before the conversion\&. \fP"
.ti -1c
.RI "file \fBlibdatetimetz_converter_prereqs\&.h\fP"
.br
.RI "\fIProvides some functions to validate the requirements before the conversion\&. \fP"
.ti -1c
.RI "file \fBlibdatetimetz_converter_tzanytype\&.h\fP"
.br
.RI "\fIProvides some functions to handle timestamps defined with any type of timezone\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Provides some functions to convert timestamp between timezone, using the zoneinfo databases\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for datetimetz-converter-lib-0\&.5 from the source code\&.
