.TH "Routines to enforce the timestamp (Date-Time)" 3 "Thu Jul 23 2015" "datetimetz-converter-lib-0.5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Routines to enforce the timestamp (Date-Time) \- 
.PP
Provides some functions to enforce validity of a given timestamp\&.  

.SS "Files"

.in +1c
.ti -1c
.RI "file \fBlibdatetimetz_converter_assert\&.h\fP"
.br
.RI "\fIProvides some functions to validate the requirements before the conversion\&. \fP"
.ti -1c
.RI "file \fBlibdatetimetz_converter_iso8601assert\&.h\fP"
.br
.RI "\fIProvides some functions to validate the requirements before the conversion\&. \fP"
.ti -1c
.RI "file \fBlibdatetimetz_converter_iso8601verifier\&.h\fP"
.br
.RI "\fIProvides some functions to compare results after timezone conversion\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Provides some functions to enforce validity of a given timestamp\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for datetimetz-converter-lib-0\&.5 from the source code\&.
