.TH "Routines to adjust values (timestamp, TZ) while processing the data" 3 "Fri Jul 24 2015" "datetimetz-converter-lib-0.5.2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Routines to adjust values (timestamp, TZ) while processing the data \- 
.PP
Provides some functions to adjust the values (timestamp, TZ) in the routine\&.  

.SS "Files"

.in +1c
.ti -1c
.RI "file \fBlibdatetimetz_converter_tztimeoffset\&.h\fP"
.br
.RI "\fIProvides some functions to handle a timezone given as a time offset\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Provides some functions to adjust the values (timestamp, TZ) in the routine\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for datetimetz-converter-lib-0\&.5\&.2 from the source code\&.
