include/libdatetimetz_converter_tzanytype.h
NAME
include/libdatetimetz_converter_tzanytype.h -
Provides some functions to handle timestamps defined with any type of timezone.
SYNOPSIS
#include <time.h>
#include 'libdatetimetz_converter_parameter.h'
Functions
int convertTimestampTZByFmtStr2Epochtimet (char *inTimestampStr, char *inTimestampFmtStr, char *inTZ, time_t *epochtimet)
converts a timestamp given as a string in a timezone to Epoch
int condcheckConvertTimestampTZByFmtStr2TZ (char *inTimestampStr, char *inTimestampFmtStr, char *outTimestampStr, char *outTimestampFmtStr, char *inTZ, char *outTZ, int DoCheck)
conditional checkings, then converts
int convertTimestampTZByFmtStr2TZ (char *inTimestampStr, char *inTimestampFmtStr, char *targetTimestampStr, char *targetTimestampFmtStr, char *inTZ, char *targetTZ)
converts a timestamp given as a string and the timezone to another timezone
int convertTimestampTZByFmt2TZ (char *inTimestampStr, int inTimestampFmt, char *targetTimestampStr, int targetTimestampFmt, char *inTZ, char *targetTZ)
converts a timestamp in an TZ in a custom format to a timestamp in an TZ in a custom format
int convertISOTimestampTZ2TZ (char *inTimestampStr, char *targetTimestampStr, char *inTZ, char *targetTZ)
converts an ISO8601 timestamp in a TZ to an ISO8601 timestamp in a TZ
Detailed Description
Provides some functions to handle timestamps defined with any type of timezone.
Author:
Laurent Cossin
Date:
July 2015
Definition in file libdatetimetz_converter_tzanytype.h.
Function Documentation
int condcheckConvertTimestampTZByFmtStr2TZ (char *inTimestampStr, char *inTimestampFmtStr, char *outTimestampStr, char *outTimestampFmtStr, char *inTZ, char *outTZ, intDoCheck)
conditional checkings, then converts
Definition at line 118 of file libdatetimetz_converter_tzanytype.c.
References assert_TimestampTZIsValid(), convertTimeOffsetToSeconds(), and convertTimestampTZByFmtStr2Epochtimet().
Referenced by compareTimestampBackToSameTZ(), compareTimestampToSameTZ(), and convertTimestampTZByFmtStr2TZ().
int convertISOTimestampTZ2TZ (char *inTimestampStr, char *targetTimestampStr, char *inTZ, char *targetTZ)
converts an ISO8601 timestamp in a TZ to an ISO8601 timestamp in a TZ converts a given timestamp in ISO8601 format and a TZ (inTZ) to a timestamp in ISO8601 format in a TZ (targetTZ)
Definition at line 362 of file libdatetimetz_converter_tzanytype.c.
References assert_isISO8601TZ(), and convertTimestampTZByFmt2TZ().
int convertTimestampTZByFmt2TZ (char *inTimestampStr, intinTimestampFmt, char *targetTimestampStr, inttargetTimestampFmt, char *inTZ, char *targetTZ)
converts a timestamp in an TZ in a custom format to a timestamp in an TZ in a custom format converts a given timestamp in a format (inTimestampFmt) and TZ (inTZ) to a timestamp in a format (targetTimestampFmt) in an TZ (targetTZ)
Definition at line 294 of file libdatetimetz_converter_tzanytype.c.
References convertTimestampTZByFmtStr2TZ().
Referenced by convertISOTimestampTZ2TZ().
int convertTimestampTZByFmtStr2Epochtimet (char *inTimestampStr, char *inTimestampFmtStr, char *inTZ, time_t *epochtimet)
converts a timestamp given as a string in a timezone to Epoch converts a timestamp given as a string in a TZ to Epoch (time_t)
input : inTimestampStr, inTZ output : epochtimet (time_t)
Definition at line 38 of file libdatetimetz_converter_tzanytype.c.
References convertTimeOffsetToSeconds(), and convertTimestampStr2Epochtimet().
Referenced by condcheckConvertTimestampTZByFmtStr2TZ().
int convertTimestampTZByFmtStr2TZ (char *inTimestampStr, char *inTimestampFmtStr, char *targetTimestampStr, char *targetTimestampFmtStr, char *inTZ, char *targetTZ)
converts a timestamp given as a string and the timezone to another timezone converts a timestamp given as a string (inTimeStr) and its timezone (inTZ) to another timezone (targetTZ)
input : inTimeStr - timestamp given for the timezone inTZ, targetTZ - target timezone
output : targetTimeStr - timestamp converted to the target timezone targetTZ
Definition at line 236 of file libdatetimetz_converter_tzanytype.c.
References condcheckConvertTimestampTZByFmtStr2TZ().
Referenced by convertTimestampTZByFmt2TZ(), and main().
Author
Generated automatically by Doxygen for datetimetz-converter-lib-0.5.2 from the source code.