src/libdatetimetz_converter_timestampverifier.c
NAME
src/libdatetimetz_converter_timestampverifier.c -
SYNOPSIS
#include <time.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include 'libtrace.h'
#include 'libdatetimetz_converter_timestamptzformat.h'
#include 'libdatetimetz_converter_tzanytype.h'
#include 'libdatetimetz_converter_timestampverifier.h'
#include 'libdatetimetz_converter_tztimeoffset.h'
#include 'libdatetimetz_converter_datatypes.h'
Functions
int compareTimestampsNoTZ (char *timestamp, char *expectedtimestamp)
int compareTimestampToSameTZ (char *inTimestampStr, char *inTimestampFmtStr, char *inTZ)
compares a timestamp (in a custom format) after conversion to the same timezone
int compareTimestampBackToSameTZ (char *inTimestampStr, char *inTimestampFmtStr, char *inTZ, char *targetTZ)
compares a timestamp (in a custom format) after conversion to another timezone and back to the original timezone
int checkTimestampConsistency (char *inTimestampNoTZStr, char *inTimestampFmtStr, char *inTZ)
checks if the timestamp (with a custom format) + timezone is consistent
Function Documentation
int checkTimestampConsistency (char *inTimestampNoTZStr, char *inTimestampFmtStr, char *inTZ)
checks if the timestamp (with a custom format) + timezone is consistent
Definition at line 156 of file libdatetimetz_converter_timestampverifier.c.
References compareTimestampBackToSameTZ(), compareTimestampToSameTZ(), and isTimeOffsetTZ().
Referenced by assert_TimestampTZIsValid().
int compareTimestampBackToSameTZ (char *inTimestampStr, char *inTimestampFmtStr, char *inTZ, char *targetTZ)
compares a timestamp (in a custom format) after conversion to another timezone and back to the original timezone
Remarks:
The expected final timestamp is the same string as the original one as input parameter
Parameters:
inTimestampStr The timestamp string
inTimestampFmtStr The format of the timestamp string
inTZ The timezone
targetTZ The target timezone
Returns:
return value of strcmp comparing the timestamp with the expected timestamp
Return values:
0 : timestamp matches the expected timestamp
<>0 : return value of the strcmp function
< timestamp in the target timezone
< timestamp back in the original timezone
Definition at line 93 of file libdatetimetz_converter_timestampverifier.c.
References compareTimestampsNoTZ(), and condcheckConvertTimestampTZByFmtStr2TZ().
Referenced by checkTimestampConsistency(), and compareISOTimestampTZBackToSameTZ().
int compareTimestampsNoTZ (char *timestamp, char *expectedtimestamp)
Definition at line 35 of file libdatetimetz_converter_timestampverifier.c.
Referenced by compareTimestampBackToSameTZ(), and compareTimestampToSameTZ().
int compareTimestampToSameTZ (char *inTimestampStr, char *inTimestampFmtStr, char *inTZ)
compares a timestamp (in a custom format) after conversion to the same timezone
Parameters:
inTimestampStr The timestamp string
inTimestampFmtStr The format (string) of the timestamp
inTZ The timezone
Returns:
return value of strcmp comparing the timestamp with the expected timestamp
Return values:
0 : timestamp matches the expected timestamp
<>0 : return value of the strcmp function
Definition at line 51 of file libdatetimetz_converter_timestampverifier.c.
References compareTimestampsNoTZ(), and condcheckConvertTimestampTZByFmtStr2TZ().
Referenced by checkTimestampConsistency(), and compareISOTimestampTZToSameTZ().
Author
Generated automatically by Doxygen for datetimetz-converter-lib-0.5.3 from the source code.