include/libdatetimetz_converter_iso8601verifier.h
NAME
include/libdatetimetz_converter_iso8601verifier.h -
Provides some functions to compare results after timezone conversion.
SYNOPSIS
Macros
#define ISO8601NOTZREGEXP
#define ISO8601NOTZREGEXPEXPECTEDMATCHES
Functions
int compareISOTimestampTZToSameTZ (char *inTimestampNoTZStr, char *inTZ)
compares a timestamp (in ISO8601 format) after conversion to the same timezone
int compareISOTimestampTZBackToSameTZ (char *inTimestampNoTZStr, char *inTZ, char *targetTZ)
compares a timestamp (in ISO8601 format) after conversion to another timezone and back to the original timezone
int checkISOTimestampTZConsistency (char *inTimestampNoTZStr, char *inTZ)
checks if the given timestamp (in ISO8601 format) is consistent after some conversions
int isISO8601noTZ (char *strval)
Verifies if a string matches an ISO8601 value without any timezone.
Detailed Description
Provides some functions to compare results after timezone conversion.
Author:
Laurent Cossin
Date:
July 2015
Definition in file libdatetimetz_converter_iso8601verifier.h.
Macro Definition Documentation
#define ISO8601NOTZREGEXP
Definition at line 82 of file libdatetimetz_converter_iso8601verifier.h.
Referenced by isISO8601noTZ().
#define ISO8601NOTZREGEXPEXPECTEDMATCHES
Definition at line 84 of file libdatetimetz_converter_iso8601verifier.h.
Referenced by isISO8601noTZ().
Function Documentation
int checkISOTimestampTZConsistency (char *inTimestampNoTZStr, char *inTZ)
checks if the given timestamp (in ISO8601 format) is consistent after some conversions
Definition at line 162 of file libdatetimetz_converter_iso8601verifier.c.
References compareISOTimestampTZBackToSameTZ(), and compareISOTimestampTZToSameTZ().
Referenced by assert_isISO8601TZ().
int compareISOTimestampTZBackToSameTZ (char *inTimestampNoTZStr, char *inTZ, char *targetTZ)
compares a timestamp (in ISO8601 format) after conversion to another timezone and back to the original timezone
Remarks:
The expected final timestamp is the same string as the original one as input parameter
Parameters:
inTimestampNoTZStr The timestamp string
inTZ The timezone
targetTZ The target timezone
Returns:
return value of strcmp comparing the timestamp with the expected timestamp
Return values:
0 : timestamp matches the expected timestamp
<>0 : return value of the strcmp function
Definition at line 113 of file libdatetimetz_converter_iso8601verifier.c.
References assert_isISO8601noTZ(), and compareTimestampBackToSameTZ().
Referenced by checkISOTimestampTZConsistency().
int compareISOTimestampTZToSameTZ (char *inTimestampNoTZStr, char *inTZ)
compares a timestamp (in ISO8601 format) after conversion to the same timezone
Parameters:
inTimestampNoTZStr The timestamp string
inTZ The timezone
Returns:
return value of strcmp comparing the timestamp with the expected timestamp
Return values:
0 : timestamp matches the expected timestamp
<>0 : return value of the strcmp function
Definition at line 64 of file libdatetimetz_converter_iso8601verifier.c.
References assert_isISO8601noTZ(), and compareTimestampToSameTZ().
Referenced by checkISOTimestampTZConsistency().
int isISO8601noTZ (char *strval)
Verifies if a string matches an ISO8601 value without any timezone.
Parameters:
strval The string to evaluate
Returns:
The result of the test
Return values:
0 if strval is an ISO8601 value
<>0 if strval is NOT an ISO8601 value
Definition at line 37 of file libdatetimetz_converter_iso8601verifier.c.
References ISO8601NOTZREGEXP, and ISO8601NOTZREGEXPEXPECTEDMATCHES.
Referenced by assert_isISO8601noTZ().
Author
Generated automatically by Doxygen for datetimetz-converter-lib-0.5 from the source code.