include/libdatetimetz_converter_iso8601assert.h
NAME
include/libdatetimetz_converter_iso8601assert.h -
Provides some functions to validate the requirements before the conversion.
SYNOPSIS
Functions
int assert_isISO8601noTZ (char *strval)
Verifies if a string is a valid ISO8601 timestamp or Abort.
int assert_isISO8601TZ (char *timestamp, char *timezone)
Verifies if a timestamp (ISO8601 format) + timezone is consistent.
Detailed Description
Provides some functions to validate the requirements before the conversion.
Author:
Laurent Cossin
Date:
July 2015
Definition in file libdatetimetz_converter_iso8601assert.h.
Function Documentation
int assert_isISO8601noTZ (char *strval)
Verifies if a string is a valid ISO8601 timestamp or Abort.
Definition at line 33 of file libdatetimetz_converter_iso8601assert.c.
References isISO8601noTZ().
Referenced by assert_isISO8601TZ(), compareISOTimestampTZBackToSameTZ(), and compareISOTimestampTZToSameTZ().
int assert_isISO8601TZ (char *timestamp, char *timezone)
Verifies if a timestamp (ISO8601 format) + timezone is consistent.
Definition at line 64 of file libdatetimetz_converter_iso8601assert.c.
References assert_isISO8601noTZ(), and checkISOTimestampTZConsistency().
Referenced by convertISOTimestampTZ2TZ().
Author
Generated automatically by Doxygen for datetimetz-converter-lib-0.9 from the source code.