.TH "include/libdatetimetz_converter_prereqs.h" 3 "Tue Jul 21 2015" "datetimetz-converter-lib-0.9" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/libdatetimetz_converter_prereqs.h \- 
.PP
Provides some functions to validate the requirements before the conversion\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBisTimestampConsistentorAbort\fP (char *timestamp, char *timestampformat, char *timezone, int abortOnFailure)"
.br
.RI "\fIChecks if the timestamp (with a custom format) is consistent\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Provides some functions to validate the requirements before the conversion\&. 


.PP
\fBAuthor:\fP
.RS 4
Laurent Cossin 
.RE
.PP
\fBDate:\fP
.RS 4
July 2015 
.RE
.PP

.PP
Definition in file \fBlibdatetimetz_converter_prereqs\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "int isTimestampConsistentorAbort (char *timestamp, char *timestampformat, char *timezone, intabortOnFailure)"

.PP
Checks if the timestamp (with a custom format) is consistent\&. 
.PP
Definition at line 31 of file libdatetimetz_converter_prereqs\&.c\&.
.PP
References checkTimestampConsistency()\&.
.PP
Referenced by condcheckConvertTimestampTZByFmtStr2TZ()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for datetimetz-converter-lib-0\&.9 from the source code\&.
