src/libdatetimetz_converter_tztimeoffset.c
NAME
src/libdatetimetz_converter_tztimeoffset.c -
SYNOPSIS
#include <time.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include 'libtrace.h'
#include 'libregex_custom.h'
#include 'libdatetimetz_converter_timestamptzformat.h'
#include 'libdatetimetz_converter_tzanytype.h'
#include 'libdatetimetz_converter_datatypes.h'
#include 'libdatetimetz_converter_timestampverifier.h'
#include 'libdatetimetz_converter_tztimeoffset.h'
Functions
int isUTCTimeOffsetTZ (char *TZval)
Verifies if a given TZ value is a valid time offset for UTC - cf ISO8601 rules.
int isTimeOffsetTZ (char *TZval)
Verifies if a given TZ value is a valid time offset.
int convertTimeOffsetToSeconds (char *TZval, int *offsetSeconds)
Converts a time offset TZ to seconds.
int splitTimeOffsetStrToValues (char *timeoffsetstr, int *signfactor, int *hours, int *minutes)
int splitconvertTimeOffsetStrToValues (char *timeoffsetstr, int *timeoffsetseconds)
Splits and converts a time string into seconds.
Function Documentation
int convertTimeOffsetToSeconds (char *TZval, int *offsetSeconds)
Converts a time offset TZ to seconds.
Definition at line 122 of file libdatetimetz_converter_tztimeoffset.c.
References isTimeOffsetTZ(), isUTCTimeOffsetTZ(), and splitconvertTimeOffsetStrToValues().
Referenced by condcheckConvertTimestampTZByFmtStr2TZ(), and convertTimestampTZByFmtStr2Epochtimet().
int isTimeOffsetTZ (char *TZval)
Verifies if a given TZ value is a valid time offset.
Definition at line 78 of file libdatetimetz_converter_tztimeoffset.c.
References OFFSETTZREGEXP, OFFSETTZREGEXPEXPECTEDMATCHES_MAX, OFFSETTZREGEXPEXPECTEDMATCHES_MIN, UTCWRONGOFFSETTZREGEXP, UTCWRONGOFFSETTZREGEXPEXPECTEDMATCHES_MAX, and UTCWRONGOFFSETTZREGEXPEXPECTEDMATCHES_MIN.
Referenced by checkTimestampConsistency(), and convertTimeOffsetToSeconds().
int isUTCTimeOffsetTZ (char *TZval)
Verifies if a given TZ value is a valid time offset for UTC - cf ISO8601 rules.
Definition at line 36 of file libdatetimetz_converter_tztimeoffset.c.
References UTCOFFSETTZREGEXP, UTCOFFSETTZREGEXPEXPECTEDMATCHES_MAX, UTCOFFSETTZREGEXPEXPECTEDMATCHES_MIN, UTCSPECIALOFFSETTZREGEXP, and UTCSPECIALOFFSETTZREGEXPEXPECTEDMATCHES.
Referenced by convertTimeOffsetToSeconds().
int splitconvertTimeOffsetStrToValues (char *timeoffsetstr, int *timeoffsetseconds)
Splits and converts a time string into seconds.
Definition at line 211 of file libdatetimetz_converter_tztimeoffset.c.
References splitTimeOffsetStrToValues().
Referenced by convertTimeOffsetToSeconds().
int splitTimeOffsetStrToValues (char *timeoffsetstr, int *signfactor, int *hours, int *minutes)
timeoffsetstr can be [sign][hh][mm] or [sign][hh]:[mm] hours are the 2 first digits (after the leading sign) minutes are the 2 trailing digits
extracts the sign of the offset
Definition at line 160 of file libdatetimetz_converter_tztimeoffset.c.
Referenced by splitconvertTimeOffsetStrToValues().
Author
Generated automatically by Doxygen for datetimetz-converter-lib-0.5.3 from the source code.