.TH "src/libdatetimetz_converter_prereqs.c" 3 "Tue Jul 21 2015" "datetimetz-converter-lib-0.9" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/libdatetimetz_converter_prereqs.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'libtrace\&.h'\fP
.br
\fC#include 'libdatetimetz_converter_consistency\&.h'\fP
.br
\fC#include 'libdatetimetz_converter_prereqs\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBisTimestampConsistentorAbort\fP (char *timestamp, char *timestampformat, char *timezone, int abortOnFailure)"
.br
.RI "\fIChecks if the timestamp (with a custom format) is consistent\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "int isTimestampConsistentorAbort (char *timestamp, char *timestampformat, char *timezone, intabortOnFailure)"

.PP
Checks if the timestamp (with a custom format) is consistent\&. 
.PP
Definition at line 31 of file libdatetimetz_converter_prereqs\&.c\&.
.PP
References checkTimestampConsistency()\&.
.PP
Referenced by condcheckConvertTimestampTZByFmtStr2TZ()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for datetimetz-converter-lib-0\&.9 from the source code\&.
