include/libdatetimetz_converter_tztimeoffset.h
NAME
include/libdatetimetz_converter_tztimeoffset.h -
Provides some functions to handle a timezone given as a time offset.
SYNOPSIS
Macros
#define UTCSPECIALOFFSETTZREGEXP
#define UTCSPECIALOFFSETTZREGEXPEXPECTEDMATCHES
#define UTCOFFSETTZREGEXP
#define UTCOFFSETTZREGEXPEXPECTEDMATCHES_MIN
#define UTCOFFSETTZREGEXPEXPECTEDMATCHES_MAX
#define UTCWRONGOFFSETTZREGEXP
#define UTCWRONGOFFSETTZREGEXPEXPECTEDMATCHES_MIN
#define UTCWRONGOFFSETTZREGEXPEXPECTEDMATCHES_MAX
#define OFFSETTZREGEXP
#define OFFSETTZREGEXPEXPECTEDMATCHES_MIN
#define OFFSETTZREGEXPEXPECTEDMATCHES_MAX
Functions
int isUTCTimeOffsetTZ (char *TZval)
Verifies if a given TZ value is a valid time offset for UTC - cf ISO8601 rules.
int isTimeOffsetTZ (char *TZval)
Verifies if a given TZ value is a valid time offset.
int convertTimeOffsetToSeconds (char *TZval, int *offsetSeconds)
Converts a time offset TZ to seconds.
int splitTimeOffseStrtToValues (char *timeoffsetstr, int *signfactor, int *hours, int *minutes)
Splits a time string into hours and minutes, and sign factor (1 or -1)
int splitconvertTimeOffsetStrToValues (char *timeoffsetstr, int *timeoffsetseconds)
Splits and converts a time string into seconds.
Detailed Description
Provides some functions to handle a timezone given as a time offset.
Author:
Laurent Cossin
Date:
July 2015
Definition in file libdatetimetz_converter_tztimeoffset.h.
Macro Definition Documentation
#define OFFSETTZREGEXP
Definition at line 55 of file libdatetimetz_converter_tztimeoffset.h.
Referenced by isTimeOffsetTZ().
#define OFFSETTZREGEXPEXPECTEDMATCHES_MAX
Definition at line 59 of file libdatetimetz_converter_tztimeoffset.h.
Referenced by isTimeOffsetTZ().
#define OFFSETTZREGEXPEXPECTEDMATCHES_MIN
Definition at line 58 of file libdatetimetz_converter_tztimeoffset.h.
Referenced by isTimeOffsetTZ().
#define UTCOFFSETTZREGEXP
Definition at line 42 of file libdatetimetz_converter_tztimeoffset.h.
Referenced by isUTCTimeOffsetTZ().
#define UTCOFFSETTZREGEXPEXPECTEDMATCHES_MAX
Definition at line 44 of file libdatetimetz_converter_tztimeoffset.h.
Referenced by isUTCTimeOffsetTZ().
#define UTCOFFSETTZREGEXPEXPECTEDMATCHES_MIN
Definition at line 43 of file libdatetimetz_converter_tztimeoffset.h.
Referenced by isUTCTimeOffsetTZ().
#define UTCSPECIALOFFSETTZREGEXP
Definition at line 38 of file libdatetimetz_converter_tztimeoffset.h.
Referenced by isUTCTimeOffsetTZ().
#define UTCSPECIALOFFSETTZREGEXPEXPECTEDMATCHES
Definition at line 39 of file libdatetimetz_converter_tztimeoffset.h.
Referenced by isUTCTimeOffsetTZ().
#define UTCWRONGOFFSETTZREGEXP
Definition at line 47 of file libdatetimetz_converter_tztimeoffset.h.
Referenced by isTimeOffsetTZ().
#define UTCWRONGOFFSETTZREGEXPEXPECTEDMATCHES_MAX
Definition at line 49 of file libdatetimetz_converter_tztimeoffset.h.
Referenced by isTimeOffsetTZ().
#define UTCWRONGOFFSETTZREGEXPEXPECTEDMATCHES_MIN
Definition at line 48 of file libdatetimetz_converter_tztimeoffset.h.
Referenced by isTimeOffsetTZ().
Function Documentation
int convertTimeOffsetToSeconds (char *TZval, int *offsetSeconds)
Converts a time offset TZ to seconds.
Definition at line 122 of file libdatetimetz_converter_tztimeoffset.c.
References isTimeOffsetTZ(), isUTCTimeOffsetTZ(), and splitconvertTimeOffsetStrToValues().
Referenced by condcheckConvertTimestampTZByFmtStr2TZ(), and convertTimestampTZByFmtStr2Epochtimet().
int isTimeOffsetTZ (char *TZval)
Verifies if a given TZ value is a valid time offset.
Definition at line 78 of file libdatetimetz_converter_tztimeoffset.c.
References OFFSETTZREGEXP, OFFSETTZREGEXPEXPECTEDMATCHES_MAX, OFFSETTZREGEXPEXPECTEDMATCHES_MIN, UTCWRONGOFFSETTZREGEXP, UTCWRONGOFFSETTZREGEXPEXPECTEDMATCHES_MAX, and UTCWRONGOFFSETTZREGEXPEXPECTEDMATCHES_MIN.
Referenced by checkTimestampConsistency(), and convertTimeOffsetToSeconds().
int isUTCTimeOffsetTZ (char *TZval)
Verifies if a given TZ value is a valid time offset for UTC - cf ISO8601 rules.
Definition at line 36 of file libdatetimetz_converter_tztimeoffset.c.
References UTCOFFSETTZREGEXP, UTCOFFSETTZREGEXPEXPECTEDMATCHES_MAX, UTCOFFSETTZREGEXPEXPECTEDMATCHES_MIN, UTCSPECIALOFFSETTZREGEXP, and UTCSPECIALOFFSETTZREGEXPEXPECTEDMATCHES.
Referenced by convertTimeOffsetToSeconds().
int splitconvertTimeOffsetStrToValues (char *timeoffsetstr, int *timeoffsetseconds)
Splits and converts a time string into seconds.
Definition at line 211 of file libdatetimetz_converter_tztimeoffset.c.
References splitTimeOffsetStrToValues().
Referenced by convertTimeOffsetToSeconds().
int splitTimeOffseStrtToValues (char *timeoffsetstr, int *signfactor, int *hours, int *minutes)
Splits a time string into hours and minutes, and sign factor (1 or -1)
Author
Generated automatically by Doxygen for datetimetz-converter-lib-0.5.2 from the source code.