src/libdatetimetz_converter_tzanytype.c
NAME
src/libdatetimetz_converter_tzanytype.c -
SYNOPSIS
#include 'config.h'
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include 'libtrace.h'
#include 'libassert_custom.h'
#include 'libdatetimetz_converter_timestamptzformat.h'
#include 'libdatetimetz_converter_epoch.h'
#include 'libdatetimetz_converter_tzanytype.h'
#include 'libdatetimetz_converter_iso8601assert.h'
#include 'libdatetimetz_converter_assert.h'
Functions
int convertTimestampTZByFmtStr2Epochtimet (char *inTimestampStr, char *inTimestampFmtStr, char *inTZ, time_t *epochtimet)
converts a timestamp given as a string in a timezone to Epoch
int condcheckConvertTimestampTZByFmtStr2TZ (char *inTimestampStr, char *inTimestampFmtStr, char *targetTimestampStr, char *targetTimestampFmtStr, char *inTZ, char *targetTZ, int DoCheck)
conditional checkings, then converts
int convertTimestampTZByFmtStr2TZ (char *inTimestampStr, char *inTimestampFmtStr, char *targetTimestampStr, char *targetTimestampFmtStr, char *inTZ, char *targetTZ)
converts a timestamp given as a string and the timezone to another timezone
int convertTimestampTZByFmt2TZ (char *inTimestampStr, int inTimestampFmt, char *targetTimestampStr, int targetTimestampFmt, char *inTZ, char *targetTZ)
converts a timestamp in an TZ in a custom format to a timestamp in an TZ in a custom format
int convertISOTimestampTZ2TZ (char *inTimestampStr, char *targetTimestampStr, char *inTZ, char *targetTZ)
converts an ISO8601 timestamp in a TZ to an ISO8601 timestamp in a TZ
Function Documentation
int condcheckConvertTimestampTZByFmtStr2TZ (char *inTimestampStr, char *inTimestampFmtStr, char *targetTimestampStr, char *targetTimestampFmtStr, char *inTZ, char *targetTZ, intDoCheck)
conditional checkings, then converts
Definition at line 86 of file libdatetimetz_converter_tzanytype.c.
References assert_TimestampTZIsValid(), and convertTimestampTZByFmtStr2Epochtimet().
Referenced by compareTimestampBackToSameTZ(), compareTimestampToSameTZ(), and convertTimestampTZByFmtStr2TZ().
int convertISOTimestampTZ2TZ (char *inTimestampStr, char *targetTimestampStr, char *inTZ, char *targetTZ)
converts an ISO8601 timestamp in a TZ to an ISO8601 timestamp in a TZ converts a given timestamp in ISO8601 format and a TZ (inTZ) to a timestamp in ISO8601 format in a TZ (targetTZ)
Definition at line 280 of file libdatetimetz_converter_tzanytype.c.
References assert_isISO8601TZ(), and convertTimestampTZByFmt2TZ().
int convertTimestampTZByFmt2TZ (char *inTimestampStr, intinTimestampFmt, char *targetTimestampStr, inttargetTimestampFmt, char *inTZ, char *targetTZ)
converts a timestamp in an TZ in a custom format to a timestamp in an TZ in a custom format converts a given timestamp in a format (inTimestampFmt) and TZ (inTZ) to a timestamp in a format (targetTimestampFmt) in an TZ (targetTZ)
Definition at line 212 of file libdatetimetz_converter_tzanytype.c.
References convertTimestampTZByFmtStr2TZ().
Referenced by convertISOTimestampTZ2TZ().
int convertTimestampTZByFmtStr2Epochtimet (char *inTimestampStr, char *inTimestampFmtStr, char *inTZ, time_t *epochtimet)
converts a timestamp given as a string in a timezone to Epoch converts a timestamp given as a string in a TZ to Epoch (time_t)
input : inTimestampStr, inTZ output : epochtimet (time_t)
Definition at line 36 of file libdatetimetz_converter_tzanytype.c.
References convertTimestampStr2Epochtimet().
Referenced by condcheckConvertTimestampTZByFmtStr2TZ().
int convertTimestampTZByFmtStr2TZ (char *inTimestampStr, char *inTimestampFmtStr, char *targetTimestampStr, char *targetTimestampFmtStr, char *inTZ, char *targetTZ)
converts a timestamp given as a string and the timezone to another timezone converts a timestamp given as a string (inTimeStr) and its timezone (inTZ) to another timezone (targetTZ)
input : inTimeStr - timestamp given for the timezone inTZ, targetTZ - target timezone
output : targetTimeStr - timestamp converted to the target timezone targetTZ
Definition at line 154 of file libdatetimetz_converter_tzanytype.c.
References condcheckConvertTimestampTZByFmtStr2TZ().
Referenced by convertTimestampTZByFmt2TZ(), and main().
Author
Generated automatically by Doxygen for datetimetz-converter-lib-0.5 from the source code.