src/libassert_custom.c
NAME
src/libassert_custom.c -
SYNOPSIS
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include 'libassert_custom.h'
#include 'libtrace.h'
Functions
int assert_pointer_is_not_null (void *ptr, char *ptrname)
int assert_string_is_not_null (char *string, char *stringname)
Function Documentation
int assert_pointer_is_not_null (void *ptr, char *ptrname)
Definition at line 28 of file libassert_custom.c.
References log_debug(), log_exit_critical(), and TRACE_MESSAGE_MAXLENGTH.
Referenced by initFmtStr().
int assert_string_is_not_null (char *string, char *stringname)
Definition at line 47 of file libassert_custom.c.
References log_debug(), log_exit_critical(), and TRACE_MESSAGE_MAXLENGTH.
Author
Generated automatically by Doxygen for datetimetz-converter-libhelper-0.5 from the source code.