include/libassert_custom.h
NAME
include/libassert_custom.h -
Provides some custom 'assert' routines.
SYNOPSIS
Functions
int assert_pointer_is_not_null (void *ptr, char *ptrname)
int assert_string_is_not_null (char *string, char *stringname)
Detailed Description
Provides some custom 'assert' routines.
Author:
Laurent Cossin
Copyright:
GNU Lesser General Public License
Date:
July 2015
Definition in file libassert_custom.h.
Function Documentation
int assert_pointer_is_not_null (void *ptr, char *ptrname)
Definition at line 28 of file libassert_custom.c.
References log_debug(), log_exit_critical(), and TRACE_MESSAGE_MAXLENGTH.
Referenced by initFmtStr().
int assert_string_is_not_null (char *string, char *stringname)
Definition at line 47 of file libassert_custom.c.
References log_debug(), log_exit_critical(), and TRACE_MESSAGE_MAXLENGTH.
Author
Generated automatically by Doxygen for datetimetz-converter-libhelper-0.5.1 from the source code.