.TH "include/libdatetimetz_converter_parameter.h" 3 "Sun Jul 26 2015" "datetimetz-converter-libhelper-0.5.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/libdatetimetz_converter_parameter.h \- 
.PP
Provides some variables\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPARAMETERS_HEADERS\fP"
.br
.ti -1c
.RI "#define \fBCONTINUEONFAILURE\fP"
.br
.RI "\fIContinue after a failure\&. \fP"
.ti -1c
.RI "#define \fBABORTONFAILURE\fP"
.br
.RI "\fIAbort the program after a CRITICAL error\&. \fP"
.ti -1c
.RI "#define \fBABORTONCRITICAL\fP"
.br
.RI "\fIAbort the program after a CRITICAL error\&. \fP"
.ti -1c
.RI "#define \fBABORTONWARNING\fP"
.br
.RI "\fIAbort the program after a WARNING error\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBactionOnFailureOpts\fP"
.br
.RI "\fIThe bit flags that define the actions be done in case of failure\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Provides some variables\&. 


.PP
\fBAuthor:\fP
.RS 4
Laurent Cossin 
.RE
.PP
\fBCopyright:\fP
.RS 4
GNU Lesser General Public License
.RE
.PP
\fBDate:\fP
.RS 4
July 2015 
.RE
.PP

.PP
Definition in file \fBlibdatetimetz_converter_parameter\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define ABORTONCRITICAL"

.PP
Abort the program after a CRITICAL error\&. 
.PP
Definition at line 54 of file libdatetimetz_converter_parameter\&.h\&.
.SS "#define ABORTONFAILURE"

.PP
Abort the program after a CRITICAL error\&. 
.PP
Definition at line 51 of file libdatetimetz_converter_parameter\&.h\&.
.SS "#define ABORTONWARNING"

.PP
Abort the program after a WARNING error\&. 
.PP
Definition at line 57 of file libdatetimetz_converter_parameter\&.h\&.
.SS "#define CONTINUEONFAILURE"

.PP
Continue after a failure\&. 
.PP
Definition at line 48 of file libdatetimetz_converter_parameter\&.h\&.
.SS "#define PARAMETERS_HEADERS"

.PP
Definition at line 43 of file libdatetimetz_converter_parameter\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "int actionOnFailureOpts"

.PP
The bit flags that define the actions be done in case of failure\&. 
.PP
Definition at line 60 of file libdatetimetz_converter_parameter\&.h\&.
.PP
Referenced by log_exit_critical()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for datetimetz-converter-libhelper-0\&.5\&.1 from the source code\&.
