.TH "include/libdatetimetz_converter_dataparsetimestamps.h" 3 "Sun Jul 26 2015" "datetimetz-converter-libhelper-0.5.1" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/libdatetimetz_converter_dataparsetimestamps.h \- 
.PP
Provides some functions to handle the data for tests\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'libdatetimetz_converter_datatypes\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBparseRawString\fP (char *rawTimestampTZStr, char *outTimestampStrNoTZ, char *outOlsonTZ)"
.br
.RI "\fIparses a row from the input file \fP"
.in -1c
.SH "Detailed Description"
.PP 
Provides some functions to handle the data for tests\&. 


.PP
\fBAuthor:\fP
.RS 4
Laurent Cossin 
.RE
.PP
\fBCopyright:\fP
.RS 4
GNU Lesser General Public License
.RE
.PP
\fBDate:\fP
.RS 4
July 2015 
.RE
.PP

.PP
Definition in file \fBlibdatetimetz_converter_dataparsetimestamps\&.h\fP\&.
.SH "Function Documentation"
.PP 
.SS "int parseRawString (char *rawTimestampTZStr, char *outTimestampStrNoTZ, char *outOlsonTZ)"

.PP
parses a row from the input file 
.PP
Definition at line 30 of file libdatetimetz_converter_dataparsetimestamps\&.c\&.
.PP
References log_debug(), and RAWTIMESTAMPMAXLENGTH\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for datetimetz-converter-libhelper-0\&.5\&.1 from the source code\&.
