include/libdatetimetz_converter_timestamptzformat.h
NAME
include/libdatetimetz_converter_timestamptzformat.h -
Provides some constants and some functions to manage the timestamp formats.
SYNOPSIS
#include 'libdatetimetz_converter_datatypes.h'
Macros
#define TIMESTAMPFORMATMAXLENGTH
Functions
int buildFmtStr (int FmtFlags, char *FmtStr)
builds the format string according to the options (FmtFlags)
int setDefaultInputFmtOpts (int *flags)
set the default options for a timestamp as input
int setDefaultOutputFmtOpts (int *flags)
set the default options for a timestamp as output
int setOlsonOpts (int *flags)
enables Olson timezone option
int setISO8601Opts (int *flags)
enables the ISO8601 format
int setISO8601OlsonOpts (int *flags)
enables ISO8601 format + Olson timezone
int setOlsonInputFmtOpts (int *flags)
enables option Olson timezone - wrapper for setOlsonOpts
int setOlsonOutputFmtOpts (int *flags)
enables option Olson timezone - wrapper for setOlsonOpts
Variables
const int iso8601Flag
ISO8601 format option.
const int TZAbbrevFlag
Timezone abbreviation option.
const int TZOffsetFlag
Timezone offset option.
const int PosixFlag
Posix format option.
const int TZOlsonFlag
Olson timezone option.
const char TZOffsetFmt []
strptime - timezone offset
const char TZAbbrevFmt []
strptime - timezone abbreviation
const char iso8601noTZFmt []
strptime - ISO8601 without timezone
const char iso8601TZOffset []
strptime - ISO8601 + timezone offset
const char iso8601TZAbbrev []
strptime - ISO8601 + timezone abbreviation
const char iso8601TZCombined []
strptime - ISO8601 + timezone offset + timezone abbreviation
Detailed Description
Provides some constants and some functions to manage the timestamp formats.
Author:
Laurent Cossin
Date:
July 2015
Definition in file libdatetimetz_converter_timestamptzformat.h.
Macro Definition Documentation
#define TIMESTAMPFORMATMAXLENGTH
Definition at line 65 of file libdatetimetz_converter_timestamptzformat.h.
Function Documentation
int buildFmtStr (intFmtFlags, char *FmtStr)
builds the format string according to the options (FmtFlags)
Definition at line 231 of file libdatetimetz_converter_timestamptzformat.c.
References appendISO8601noTZ(), appendTZAbbrev(), initFmtStr(), isISO8601(), and isTZAbbrev().
int setDefaultInputFmtOpts (int *flags)
set the default options for a timestamp as input
Definition at line 83 of file libdatetimetz_converter_timestamptzformat.c.
References setISO8601Opts().
int setDefaultOutputFmtOpts (int *flags)
set the default options for a timestamp as output
Definition at line 94 of file libdatetimetz_converter_timestamptzformat.c.
References iso8601Flag, and TZAbbrevFlag.
int setISO8601OlsonOpts (int *flags)
enables ISO8601 format + Olson timezone
Definition at line 52 of file libdatetimetz_converter_timestamptzformat.c.
References setISO8601Opts(), and setOlsonOpts().
int setISO8601Opts (int *flags)
enables the ISO8601 format
Definition at line 43 of file libdatetimetz_converter_timestamptzformat.c.
References iso8601Flag.
Referenced by setDefaultInputFmtOpts(), and setISO8601OlsonOpts().
int setOlsonInputFmtOpts (int *flags)
enables option Olson timezone - wrapper for setOlsonOpts
Definition at line 63 of file libdatetimetz_converter_timestamptzformat.c.
References setOlsonOpts().
int setOlsonOpts (int *flags)
enables Olson timezone option
Definition at line 33 of file libdatetimetz_converter_timestamptzformat.c.
References TZOlsonFlag.
Referenced by setISO8601OlsonOpts(), setOlsonInputFmtOpts(), and setOlsonOutputFmtOpts().
int setOlsonOutputFmtOpts (int *flags)
enables option Olson timezone - wrapper for setOlsonOpts
Definition at line 73 of file libdatetimetz_converter_timestamptzformat.c.
References setOlsonOpts().
Variable Documentation
const int iso8601Flag
ISO8601 format option.
Definition at line 47 of file libdatetimetz_converter_timestamptzformat.h.
Referenced by isISO8601(), setDefaultOutputFmtOpts(), and setISO8601Opts().
const char iso8601noTZFmt[]
strptime - ISO8601 without timezone
Definition at line 78 of file libdatetimetz_converter_timestamptzformat.h.
Referenced by appendISO8601noTZ().
const char iso8601TZAbbrev[]
strptime - ISO8601 + timezone abbreviation
Definition at line 84 of file libdatetimetz_converter_timestamptzformat.h.
const char iso8601TZCombined[]
strptime - ISO8601 + timezone offset + timezone abbreviation
Definition at line 87 of file libdatetimetz_converter_timestamptzformat.h.
const char iso8601TZOffset[]
strptime - ISO8601 + timezone offset
Definition at line 81 of file libdatetimetz_converter_timestamptzformat.h.
Referenced by formatted_now().
const int PosixFlag
Posix format option.
Definition at line 56 of file libdatetimetz_converter_timestamptzformat.h.
const int TZAbbrevFlag
Timezone abbreviation option.
Definition at line 50 of file libdatetimetz_converter_timestamptzformat.h.
Referenced by isTZAbbrev(), and setDefaultOutputFmtOpts().
const char TZAbbrevFmt[]
strptime - timezone abbreviation
Definition at line 71 of file libdatetimetz_converter_timestamptzformat.h.
Referenced by appendTZAbbrev().
const int TZOffsetFlag
Timezone offset option.
Definition at line 53 of file libdatetimetz_converter_timestamptzformat.h.
const char TZOffsetFmt[]
strptime - timezone offset
Definition at line 68 of file libdatetimetz_converter_timestamptzformat.h.
const int TZOlsonFlag
Olson timezone option.
Definition at line 59 of file libdatetimetz_converter_timestamptzformat.h.
Referenced by isTZOlson(), and setOlsonOpts().
Author
Generated automatically by Doxygen for datetimetz-converter-libhelper-0.5 from the source code.