src/libdatetimetz_converter_timestamptzformat.c
NAME
src/libdatetimetz_converter_timestamptzformat.c -
SYNOPSIS
#include 'config.h'
#include <time.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include 'libtrace.h'
#include 'libassert_custom.h'
#include 'libdatetimetz_converter_timestamptzformat.h'
Functions
int setOlsonOpts (int *flags)
enables Olson timezone option
int setISO8601Opts (int *flags)
enables the ISO8601 format
int setISO8601OlsonOpts (int *flags)
enables ISO8601 format + Olson timezone
int setOlsonInputFmtOpts (int *flags)
enables option Olson timezone - wrapper for setOlsonOpts
int setOlsonOutputFmtOpts (int *flags)
enables option Olson timezone - wrapper for setOlsonOpts
int setDefaultInputFmtOpts (int *flags)
set the default options for a timestamp as input
int setDefaultOutputFmtOpts (int *flags)
set the default options for a timestamp as output
int isISO8601 (int FmtFlags)
int isTZAbbrev (int FmtFlags)
int isTZOlson (int FmtFlags)
int append2FmtStr (char *FmtStr, const char *addStr)
int appendISO8601noTZ (char *FmtStr)
int appendTZAbbrev (char *FmtStr)
int initFmtStr (char *FmtStr)
initializes an empty string
int buildFmtStr (int FmtFlags, char *FmtStr)
builds the format string according to the options (FmtFlags)
Function Documentation
int append2FmtStr (char *FmtStr, const char *addStr)
Definition at line 139 of file libdatetimetz_converter_timestamptzformat.c.
Referenced by appendISO8601noTZ(), and appendTZAbbrev().
int appendISO8601noTZ (char *FmtStr)
Definition at line 180 of file libdatetimetz_converter_timestamptzformat.c.
References append2FmtStr(), and iso8601noTZFmt.
Referenced by buildFmtStr().
int appendTZAbbrev (char *FmtStr)
Definition at line 193 of file libdatetimetz_converter_timestamptzformat.c.
References append2FmtStr(), and TZAbbrevFmt.
Referenced by buildFmtStr().
int buildFmtStr (intFmtFlags, char *FmtStr)
builds the format string according to the options (FmtFlags)
Definition at line 231 of file libdatetimetz_converter_timestamptzformat.c.
References appendISO8601noTZ(), appendTZAbbrev(), initFmtStr(), isISO8601(), and isTZAbbrev().
int initFmtStr (char *FmtStr)
initializes an empty string
Definition at line 209 of file libdatetimetz_converter_timestamptzformat.c.
References assert_pointer_is_not_null().
Referenced by buildFmtStr().
int isISO8601 (intFmtFlags)
Definition at line 105 of file libdatetimetz_converter_timestamptzformat.c.
References iso8601Flag.
Referenced by buildFmtStr().
int isTZAbbrev (intFmtFlags)
Definition at line 116 of file libdatetimetz_converter_timestamptzformat.c.
References TZAbbrevFlag.
Referenced by buildFmtStr().
int isTZOlson (intFmtFlags)
Definition at line 127 of file libdatetimetz_converter_timestamptzformat.c.
References TZOlsonFlag.
int setDefaultInputFmtOpts (int *flags)
set the default options for a timestamp as input
Definition at line 83 of file libdatetimetz_converter_timestamptzformat.c.
References setISO8601Opts().
int setDefaultOutputFmtOpts (int *flags)
set the default options for a timestamp as output
Definition at line 94 of file libdatetimetz_converter_timestamptzformat.c.
References iso8601Flag, and TZAbbrevFlag.
int setISO8601OlsonOpts (int *flags)
enables ISO8601 format + Olson timezone
Definition at line 52 of file libdatetimetz_converter_timestamptzformat.c.
References setISO8601Opts(), and setOlsonOpts().
int setISO8601Opts (int *flags)
enables the ISO8601 format
Definition at line 43 of file libdatetimetz_converter_timestamptzformat.c.
References iso8601Flag.
Referenced by setDefaultInputFmtOpts(), and setISO8601OlsonOpts().
int setOlsonInputFmtOpts (int *flags)
enables option Olson timezone - wrapper for setOlsonOpts
Definition at line 63 of file libdatetimetz_converter_timestamptzformat.c.
References setOlsonOpts().
int setOlsonOpts (int *flags)
enables Olson timezone option
Definition at line 33 of file libdatetimetz_converter_timestamptzformat.c.
References TZOlsonFlag.
Referenced by setISO8601OlsonOpts(), setOlsonInputFmtOpts(), and setOlsonOutputFmtOpts().
int setOlsonOutputFmtOpts (int *flags)
enables option Olson timezone - wrapper for setOlsonOpts
Definition at line 73 of file libdatetimetz_converter_timestamptzformat.c.
References setOlsonOpts().
Author
Generated automatically by Doxygen for datetimetz-converter-libhelper-0.5 from the source code.