src/libtrace.c
NAME
src/libtrace.c -
SYNOPSIS
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include 'libtrace.h'
#include 'libdatetimetz_converter_parameter.h'
#include 'libdatetimetz_converter_timestamptzformat.h'
Functions
int formatted_now (char **nowstr)
int log_message (char *msg, int msglevel, char *msgheader)
int log_exit_critical (char *msg)
writes the given message depending on TRACE_LEVEL
int log_critical (char *msg)
Writes a 'critical' level message.
int log_warning (char *msg)
Writes a 'warning' level message.
int log_info (char *msg)
Writes a 'info' level message.
int log_fine (char *msg)
Writes a 'fine' level message.
int log_finer (char *msg)
Writes a 'fine' level message.
int log_finest (char *msg)
Writes a 'finest' level message.
int log_debug (char *msg)
Writes a 'debug' level message.
Variables
int TRACE_LEVEL
TRACE_LEVEL (variable)
Function Documentation
int formatted_now (char **nowstr)
Definition at line 32 of file libtrace.c.
References iso8601TZOffset, and TIMESTAMPMAXLENGTH.
Referenced by log_message().
int log_critical (char *msg)
Writes a 'critical' level message.
Definition at line 81 of file libtrace.c.
References log_message(), TRACE_LEVEL_CRITICAL, and TRACE_LEVEL_CRITICAL_HEADER.
Referenced by log_exit_critical().
int log_debug (char *msg)
Writes a 'debug' level message.
Definition at line 132 of file libtrace.c.
References log_message(), TRACE_LEVEL_DEBUG, and TRACE_LEVEL_DEBUG_HEADER.
Referenced by assert_pointer_is_not_null(), assert_string_is_not_null(), parseRawString(), and regexp_verify().
int log_exit_critical (char *msg)
writes the given message depending on TRACE_LEVEL Writes messages according to TRACE_LEVEL
input : msg - the message to be written
output stream : stderr (hard coded)Writes a 'critical' level message + aborts the program
Definition at line 70 of file libtrace.c.
References actionOnFailureOpts, and log_critical().
Referenced by assert_pointer_is_not_null(), and assert_string_is_not_null().
int log_fine (char *msg)
Writes a 'fine' level message.
Definition at line 105 of file libtrace.c.
References log_message(), TRACE_LEVEL_FINE, and TRACE_LEVEL_FINE_HEADER.
int log_finer (char *msg)
Writes a 'fine' level message.
Definition at line 114 of file libtrace.c.
References log_message(), TRACE_LEVEL_FINER, and TRACE_LEVEL_FINER_HEADER.
int log_finest (char *msg)
Writes a 'finest' level message.
Definition at line 123 of file libtrace.c.
References log_message(), TRACE_LEVEL_FINEST, and TRACE_LEVEL_FINEST_HEADER.
Referenced by regexp_verify().
int log_info (char *msg)
Writes a 'info' level message.
Definition at line 97 of file libtrace.c.
References log_message(), TRACE_LEVEL_INFO, and TRACE_LEVEL_INFO_HEADER.
int log_message (char *msg, intmsglevel, char *msgheader)
Definition at line 46 of file libtrace.c.
References formatted_now(), and TRACE_LEVEL.
Referenced by log_critical(), log_debug(), log_fine(), log_finer(), log_finest(), log_info(), and log_warning().
int log_warning (char *msg)
Writes a 'warning' level message.
Definition at line 89 of file libtrace.c.
References log_message(), TRACE_LEVEL_WARNING, and TRACE_LEVEL_WARNING_HEADER.
Variable Documentation
int TRACE_LEVEL
TRACE_LEVEL (variable)
Definition at line 29 of file libtrace.c.
Referenced by log_message().
Author
Generated automatically by Doxygen for datetimetz-converter-libhelper-0.5 from the source code.