include/libtrace.h
NAME
include/libtrace.h -
Provides some helper functions to handle trace messages.
SYNOPSIS
Macros
#define TRACE_MESSAGE_MAXLENGTH
TRACE MESSAGE maxlength.
#define TRACE_LEVEL_NONE
TRACE_LEVEL_NONE (constant)
#define TRACE_LEVEL_NONE_HEADER
#define TRACE_LEVEL_CRITICAL
TRACE_LEVEL_CRITICAL (constant)
#define TRACE_LEVEL_CRITICAL_HEADER
#define TRACE_LEVEL_WARNING
TRACE_LEVEL_WARNING (constant)
#define TRACE_LEVEL_WARNING_HEADER
#define TRACE_LEVEL_INFO
TRACE_LEVEL_INFO (constant)
#define TRACE_LEVEL_INFO_HEADER
#define TRACE_LEVEL_FINE
TRACE_LEVEL_FINE (constant)
#define TRACE_LEVEL_FINE_HEADER
#define TRACE_LEVEL_FINER
TRACE_LEVEL_FINER (constant)
#define TRACE_LEVEL_FINER_HEADER
#define TRACE_LEVEL_FINEST
TRACE_LEVEL_FINEST (constant)
#define TRACE_LEVEL_FINEST_HEADER
#define TRACE_LEVEL_DEBUG
TRACE_LEVEL_DEBUG (constant)
#define TRACE_LEVEL_DEBUG_HEADER
Functions
int log_exit_critical (const char *module, char *msg)
writes the given message depending on TRACE_LEVEL
int log_critical (const char *module, char *msg)
Writes a 'critical' level message.
int log_warning (const char *module, char *msg)
Writes a 'warning' level message.
int log_info (const char *module, char *msg)
Writes a 'info' level message.
int log_fine (const char *module, char *msg)
Writes a 'fine' level message.
int log_finer (const char *module, char *msg)
Writes a 'fine' level message.
int log_finest (const char *module, char *msg)
Writes a 'finest' level message.
int log_debug (const char *module, char *msg)
Writes a 'debug' level message.
Variables
int TRACE_LEVEL
TRACE_LEVEL (variable)
Detailed Description
Provides some helper functions to handle trace messages.
Author:
Laurent Cossin
Copyright:
GNU Lesser General Public License
Date:
July 2015
Definition in file libtrace.h.
Macro Definition Documentation
#define TRACE_LEVEL_CRITICAL
TRACE_LEVEL_CRITICAL (constant)
Definition at line 46 of file libtrace.h.
Referenced by log_critical().
#define TRACE_LEVEL_CRITICAL_HEADER
Definition at line 47 of file libtrace.h.
Referenced by log_critical().
#define TRACE_LEVEL_DEBUG
TRACE_LEVEL_DEBUG (constant)
Definition at line 70 of file libtrace.h.
Referenced by log_debug().
#define TRACE_LEVEL_DEBUG_HEADER
Definition at line 71 of file libtrace.h.
Referenced by log_debug().
#define TRACE_LEVEL_FINE
TRACE_LEVEL_FINE (constant)
Definition at line 58 of file libtrace.h.
Referenced by log_fine().
#define TRACE_LEVEL_FINE_HEADER
Definition at line 59 of file libtrace.h.
Referenced by log_fine().
#define TRACE_LEVEL_FINER
TRACE_LEVEL_FINER (constant)
Definition at line 62 of file libtrace.h.
Referenced by log_finer().
#define TRACE_LEVEL_FINER_HEADER
Definition at line 63 of file libtrace.h.
Referenced by log_finer().
#define TRACE_LEVEL_FINEST
TRACE_LEVEL_FINEST (constant)
Definition at line 66 of file libtrace.h.
Referenced by log_finest().
#define TRACE_LEVEL_FINEST_HEADER
Definition at line 67 of file libtrace.h.
Referenced by log_finest().
#define TRACE_LEVEL_INFO
TRACE_LEVEL_INFO (constant)
Definition at line 54 of file libtrace.h.
Referenced by log_info().
#define TRACE_LEVEL_INFO_HEADER
Definition at line 55 of file libtrace.h.
Referenced by log_info().
#define TRACE_LEVEL_NONE
TRACE_LEVEL_NONE (constant)
Definition at line 42 of file libtrace.h.
#define TRACE_LEVEL_NONE_HEADER
Definition at line 43 of file libtrace.h.
#define TRACE_LEVEL_WARNING
TRACE_LEVEL_WARNING (constant)
Definition at line 50 of file libtrace.h.
Referenced by log_warning().
#define TRACE_LEVEL_WARNING_HEADER
Definition at line 51 of file libtrace.h.
Referenced by log_warning().
#define TRACE_MESSAGE_MAXLENGTH
TRACE MESSAGE maxlength.
Definition at line 39 of file libtrace.h.
Referenced by assert_pointer_is_not_null(), assert_string_is_not_null(), and regexp_verify().
Function Documentation
int log_critical (const char *module, char *msg)
Writes a 'critical' level message.
Definition at line 81 of file libtrace.c.
References log_message(), TRACE_LEVEL_CRITICAL, and TRACE_LEVEL_CRITICAL_HEADER.
Referenced by log_exit_critical().
int log_debug (const char *module, char *msg)
Writes a 'debug' level message.
Definition at line 132 of file libtrace.c.
References log_message(), TRACE_LEVEL_DEBUG, and TRACE_LEVEL_DEBUG_HEADER.
Referenced by assert_pointer_is_not_null(), assert_string_is_not_null(), parseRawString(), and regexp_verify().
int log_exit_critical (const char *module, char *msg)
writes the given message depending on TRACE_LEVEL Writes messages according to TRACE_LEVEL
input : msg - the message to be written
output stream : stderr (hard coded)Writes a 'critical' level message + aborts the program
Definition at line 70 of file libtrace.c.
References actionOnFailureOpts, and log_critical().
Referenced by assert_pointer_is_not_null(), and assert_string_is_not_null().
int log_fine (const char *module, char *msg)
Writes a 'fine' level message.
Definition at line 105 of file libtrace.c.
References log_message(), TRACE_LEVEL_FINE, and TRACE_LEVEL_FINE_HEADER.
int log_finer (const char *module, char *msg)
Writes a 'fine' level message.
Definition at line 114 of file libtrace.c.
References log_message(), TRACE_LEVEL_FINER, and TRACE_LEVEL_FINER_HEADER.
int log_finest (const char *module, char *msg)
Writes a 'finest' level message.
Definition at line 123 of file libtrace.c.
References log_message(), TRACE_LEVEL_FINEST, and TRACE_LEVEL_FINEST_HEADER.
Referenced by regexp_verify().
int log_info (const char *module, char *msg)
Writes a 'info' level message.
Definition at line 97 of file libtrace.c.
References log_message(), TRACE_LEVEL_INFO, and TRACE_LEVEL_INFO_HEADER.
int log_warning (const char *module, char *msg)
Writes a 'warning' level message.
Definition at line 89 of file libtrace.c.
References log_message(), TRACE_LEVEL_WARNING, and TRACE_LEVEL_WARNING_HEADER.
Variable Documentation
int TRACE_LEVEL
TRACE_LEVEL (variable)
Definition at line 29 of file libtrace.c.
Referenced by log_message().
Author
Generated automatically by Doxygen for datetimetz-converter-libhelper-0.5.1 from the source code.