.TH "timezonestructdef" 3 "Fri Jul 24 2015" "datetimetz-converter-libhelper-0.5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
timezonestructdef \- 
.PP
structure definition for a timezone  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libdatetimetz_converter_datatypes\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBitemcount\fP"
.br
.ti -1c
.RI "char * \fBtzname\fP"
.br
.ti -1c
.RI "\fBtimezonestructptrdef\fP \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
structure definition for a timezone 
.PP
Definition at line 76 of file libdatetimetz_converter_datatypes\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int timezonestructdef::itemcount"

.PP
Definition at line 78 of file libdatetimetz_converter_datatypes\&.h\&.
.SS "\fBtimezonestructptrdef\fP timezonestructdef::next"

.PP
Definition at line 82 of file libdatetimetz_converter_datatypes\&.h\&.
.SS "char* timezonestructdef::tzname"

.PP
Definition at line 80 of file libdatetimetz_converter_datatypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for datetimetz-converter-libhelper-0\&.5 from the source code\&.
