.TH "timestampstructdef" 3 "Tue Jul 21 2015" "datetimetz-converter-libhelper-0.5" \" -*- nroff -*-
.ad l
.nh
.SH NAME
timestampstructdef \- 
.PP
structure definition for a timestamp  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libdatetimetz_converter_datatypes\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBitemcount\fP"
.br
.ti -1c
.RI "char * \fBrawstr\fP"
.br
.ti -1c
.RI "char * \fBtimestampnoTZstr\fP"
.br
.ti -1c
.RI "char * \fBOlsonTZ\fP"
.br
.ti -1c
.RI "\fBtimestampstructptrdef\fP \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
structure definition for a timestamp 
.PP
Definition at line 108 of file libdatetimetz_converter_datatypes\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int timestampstructdef::itemcount"

.PP
Definition at line 110 of file libdatetimetz_converter_datatypes\&.h\&.
.SS "\fBtimestampstructptrdef\fP timestampstructdef::next"

.PP
Definition at line 116 of file libdatetimetz_converter_datatypes\&.h\&.
.SS "char* timestampstructdef::OlsonTZ"

.PP
Definition at line 114 of file libdatetimetz_converter_datatypes\&.h\&.
.SS "char* timestampstructdef::rawstr"

.PP
Definition at line 112 of file libdatetimetz_converter_datatypes\&.h\&.
.SS "char* timestampstructdef::timestampnoTZstr"

.PP
Definition at line 113 of file libdatetimetz_converter_datatypes\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for datetimetz-converter-libhelper-0\&.5 from the source code\&.
